
services:
  terraform:
    image: hashicorp/terraform:1.14.3
    container_name: terraform
    working_dir: /infra
    volumes:
      - ./setup:/setup
      - ./prod:/prod
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_DEFAULT_REGION="us-east-1"
      - TF_WORKSPACE=${TF_WORKSPACE}